// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://senocoggwqvhwtjvhjqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlbm9jb2dnd3F2aHd0anZoanFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjEzMzQsImV4cCI6MjA2MzMzNzMzNH0.XvXBblEasagBM0SndSz2gymj4UmLmWDzj6pzd9CzkR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);